#!/bin/bash

# Hide "last login" line when starting a new terminal session
touch $HOME/.hushlogin

# Install zsh
echo 'Install oh-my-zsh'
echo '-----------------'
rm -rf $HOME/.oh-my-zsh
curl -L https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh | sh

# Configure git
ln -s $HOME/.dotfiles/shell/.gitconfig $HOME/.gitconfig
ln -s $HOME/.dotfiles/shell/.global-gitignore $HOME/.global-gitignore

# Symlink zsh prefs
rm $HOME/.zshrc
ln -s $HOME/.dotfiles/shell/.zshrc $HOME/.zshrc

# Symlink the Mackup config
ln -s $HOME/.dotfiles/macos/.mackup.cfg $HOME/.mackup.cfg

# Install brew dependencies
brew bundle --file "${HOME}/.dotfiles/macos/Brewfile"

echo 'Install imagick'
echo '---------------'
pecl install imagick

echo 'Install pcov'
echo '--------------'
pecl install pcov

echo 'Install redis'
echo '-------------'
pecl install redis

echo 'Install laravel valet'
echo '---------------------'
composer global require laravel/valet
valet install
mkdir -p "${HOME}/Sites"
valet park "${HOME}/Sites"
